from typing import Optional, Annotated
from typing_extensions import TypedDict
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    The state that flows between every node in the LangGraph agent.

    Every node receives this state, can read from it,
    and returns an updated version of it.

    Think of it as the agent's working memory for one conversation turn.
    """

    # ── Conversation ──────────────────────────────────────────────────────────
    # Full message history — add_messages handles appending correctly
    messages: Annotated[list, add_messages]

    # The current user question being processed
    question: str

    # ── Routing ───────────────────────────────────────────────────────────────
    # Which tools the router decided to call
    # Options: "papers", "code", "graph", "pubmed", "papers_and_code"
    route: Optional[str]

    # ── Retrieved context ─────────────────────────────────────────────────────
    # Raw context retrieved from papers vector store
    papers_context: Optional[str]

    # Raw context retrieved from code vector store
    code_context: Optional[str]

    # Structured context from knowledge graph
    graph_context: Optional[str]

    # Results fetched from PubMed
    pubmed_context: Optional[str]

    # ── Final output ──────────────────────────────────────────────────────────
    # The final answer generated by the LLM
    answer: Optional[str]

    # Sources used to generate the answer
    sources: Optional[list[str]]

    # ── Fallback flag ─────────────────────────────────────────────────────────
    # Set by reranker when local papers are insufficient — triggers PubMed
    needs_pubmed_fallback: Optional[bool]

    # ── Evaluation ────────────────────────────────────────────────────────────
    # RAGAS faithfulness score (0.0 to 1.0)
    faithfulness_score: Optional[float]

    # RAGAS answer relevancy score (0.0 to 1.0)
    relevancy_score: Optional[float]

    # Any evaluation error messages
    eval_error: Optional[str]


def get_initial_state(question: str) -> AgentState:
    """
    Returns a clean initial state for a new question.
    All optional fields start as None.
    """
    return AgentState(
        messages=[],
        question=question,
        route=None,
        papers_context=None,
        code_context=None,
        graph_context=None,
        pubmed_context=None,
        needs_pubmed_fallback=False,
        answer=None,
        sources=None,
        faithfulness_score=None,
        relevancy_score=None,
        eval_error=None
    )


if __name__ == "__main__":
    print("Testing AgentState...\n")

    state = get_initial_state("What does the Shrestha lab study?")

    print(f"Question : {state['question']}")
    print(f"Route    : {state['route']}")
    print(f"Answer   : {state['answer']}")
    print(f"Messages : {state['messages']}")

    # Simulate updating state like a node would
    state["route"] = "papers"
    state["papers_context"] = "Some retrieved context..."
    state["answer"] = "The Shrestha lab studies..."
    state["sources"] = ["Lab_Paper1.pdf", "Lab_Paper3.pdf"]
    state["faithfulness_score"] = 0.92

    print(f"\nAfter update:")
    print(f"Route             : {state['route']}")
    print(f"Papers context    : {state['papers_context']}")
    print(f"Answer            : {state['answer']}")
    print(f"Sources           : {state['sources']}")
    print(f"Faithfulness score: {state['faithfulness_score']}")

    print("\n✅ AgentState working correctly!")